const { Router } = require('express');
const authRoutes = require('./auth.routes');
const zonesRoutes = require('./zones.routes');
const locationsRoutes = require('./locations.routes');
const itinerariesRoutes = require('./itineraries.routes');
const servicesRoutes = require('./services.routes');
const providersRoutes = require('./providers.routes');
const businessUnitsRoutes = require('./business-units.routes');
const businessCategoriesRoutes = require('./business-categories.routes');
const serviceCategoriesRoutes = require('./service-categories.routes');
const serviceTagsRoutes = require('./service-tags.route');
const socialAreasRoutes = require('./social-areas.routes');
const amenitiesRoutes = require('./amenities.routes');
const securityComplianceRoutes = require('./security-compliance-items.routes');
const possibleRiskRoutes = require('./possible-risk-items.routes');
const privacyItemsRoutes = require('./privacy-items.routes');
const serviceRequirementRoutes = require('./service-requirement-items.routes');
const serviceRuleRoutes = require('./service-rules.routes');
const cancellationPolicyRoutes = require('./cancellation-policies.routes');
const activitiesRoutes = require('./activities.routes');
const googlePlacesRoutes = require('./google-places.routes');
const activityCategoriesRoutes = require('./activity-categories.routes');
const userFavoritesRoutes = require('./user-favorites.routes');
const userPreferencesRoutes = require('./user-preferences.routes');
const onboardingTrackingRoutes = require('./onboarding-tracking.routes');
const usersRoutes = require('./users.routes');
const aiRoutes = require('./ai.routes');
const emailRoutes = require('./email.routes');
const analyticsRoutes = require('./analytics.routes');
const adminRoutes = require('./admin.routes');
const adminBillingRoutes = require('./admin-billing.routes');
const billingRoutes = require('./billing.routes');
const paywallVariantsRoutes = require('./paywall-variants.routes');

const router = Router();

router.use('/auth', authRoutes);
router.use('/zones', zonesRoutes);
router.use('/locations', locationsRoutes);
router.use('/itineraries', itinerariesRoutes);
router.use('/services', servicesRoutes);
router.use('/providers', providersRoutes);
router.use('/business-units', businessUnitsRoutes);
router.use('/business-categories', businessCategoriesRoutes);
router.use('/service-categories', serviceCategoriesRoutes);
router.use('/service-tags', serviceTagsRoutes);
router.use('/social-areas', socialAreasRoutes);
router.use('/amenities', amenitiesRoutes);
router.use('/security-compliance-items', securityComplianceRoutes);
router.use('/possible-risk-items', possibleRiskRoutes);
router.use('/privacy-items', privacyItemsRoutes);
router.use('/service-requirement-items', serviceRequirementRoutes);
router.use('/service-rules', serviceRuleRoutes);
router.use('/cancellation-policies', cancellationPolicyRoutes);
router.use('/activities', activitiesRoutes);
router.use('/google-places', googlePlacesRoutes);
router.use('/activity-categories', activityCategoriesRoutes);
router.use('/user-favorites', userFavoritesRoutes);
router.use('/user-preferences', userPreferencesRoutes);
router.use('/onboarding-tracking', onboardingTrackingRoutes);
router.use('/users', usersRoutes);
router.use('/ai', aiRoutes);
router.use('/emails', emailRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/billing', billingRoutes);
router.use('/paywall-variants', paywallVariantsRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/billing', adminBillingRoutes);

module.exports = router;
